### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by arboeh** [osi1880vr/prompt_quill#19]
I' getting the following error while trying to install on Windows:

Python version is:
```
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

```
Download Qdrant
Attempt 1 to download https://github.com/qdrant/qdrant/releases/download/v1.10.0/qdrant-x86_64-pc-windows-msvc.zip
qdrant-x86_64-pc-windows-msvc.zip: 100%|█████████████████████████████████████████| 21.1M/21.1M [00:03<00:00, 6.47MiB/s]
Download Qdrant Web UI
Attempt 1 to download https://github.com/qdrant/qdrant-web-ui/releases/download/v0.1.29/dist-qdrant.zip
dist-qdrant.zip: 100%|███████████████████████████████████████████████████████████| 1.90M/1.90M [00:00<00:00, 6.33MiB/s]
Download Prompt Quill data
Attempt 1 to download https://civitai.com/api/download/models/567736
data.zip:  61%|████████████████████████████████████████                          | 8.86G/14.6G [25:09<16:14, 6.31MiB/s]
Error downloading: ('Connection broken: IncompleteRead(9518051328 bytes read, 6144434220 more expected)', IncompleteRead(9518051328 bytes read, 6144434220 more expected))
Retrying...
Attempt 2 to download https://civitai.com/api/download/models/567736
data.zip: 100%|█████████████████████████████████████████████████████████████████▉| 14.6G/14.6G [41:05<00:00, 6.35MiB/s]
Error downloading: ('Connection broken: IncompleteRead(15661072384 bytes read, 1413164 more expected)', IncompleteRead(15661072384 bytes read, 1413164 more expected))
Retrying...
Attempt 3 to download https://civitai.com/api/download/models/567736
data.zip: 100%|█████████████████████████████████████████████████████████████████▉| 14.6G/14.6G [40:51<00:00, 6.39MiB/s]
Error downloading: ('Connection broken: IncompleteRead(15661137920 bytes read, 1347628 more expected)', IncompleteRead(15661137920 bytes read, 1347628 more expected))
Retrying...
Attempt 4 to download https://civitai.com/api/download/models/567736
data.zip: 100%|█████████████████████████████████████████████████████████████████▉| 14.6G/14.6G [41:12<00:00, 6.33MiB/s]
Error downloading: ('Connection broken: IncompleteRead(15661137920 bytes read, 1347628 more expected)', IncompleteRead(15661137920 bytes read, 1347628 more expected))
Retrying...
Attempt 5 to download https://civitai.com/api/download/models/567736
data.zip:  21%|█████████████▉                                                    | 3.09G/14.6G [08:46<32:43, 6.29MiB/s]
Error downloading: ('Connection broken: IncompleteRead(3314184192 bytes read, 12348301356 more expected)', IncompleteRead(3314184192 bytes read, 12348301356 more expected))
Max retries (5) exceeded. Giving up.
Traceback (most recent call last):
  File "I:\Tools\prompt_quill\llama_index_pq\installer_files\env\Lib\site-packages\urllib3\response.py", line 748, in _error_catcher
    yield
  File "I:\Tools\prompt_quill\llama_index_pq\installer_files\env\Lib\site-packages\urllib3\response.py", line 894, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(3314184192 bytes read, 12348301356 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "I:\Tools\prompt_quill\llama_index_pq\installer_files\env\Lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "I:\Tools\prompt_quill\llama_index_pq\installer_files\env\Lib\site-packages\urllib3\response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\Tools\prompt_quill\llama_index_pq\installer_files\env\Lib\site-packages\urllib3\response.py", line 949, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "I:\Tools\prompt_quill\llama_index_pq\installer_files\env\Lib\site-packages\urllib3\response.py", line 872, in _raw_read
    with self._error_catcher():
  File "I:\Tools\prompt_quill\llama_index_pq\installer_files\env\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "I:\Tools\prompt_quill\llama_index_pq\installer_files\env\Lib\site-packages\urllib3\response.py", line 772, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(3314184192 bytes read, 12348301356 more expected)', IncompleteRead(3314184192 bytes read, 12348301356 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\Tools\prompt_quill\llama_index_pq\install_qdrant.py", line 153, in <module>
    download_qdrant()
  File "I:\Tools\prompt_quill\llama_index_pq\install_qdrant.py", line 121, in download_qdrant
    status_code = download_file(url, install_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\Tools\prompt_quill\llama_index_pq\install_qdrant.py", line 48, in download_file
    for data in response.iter_content(chunk_size=1024):
  File "I:\Tools\prompt_quill\llama_index_pq\installer_files\env\Lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(3314184192 bytes read, 12348301356 more expected)', IncompleteRead(3314184192 bytes read, 12348301356 more expected))
Performing cleanup
```
After that installing continues, but I get another error:

```
ERROR: Ignored the following versions that require a different python version: 0.11.10 Requires-Python >=3.7,<=3.11; 1.0.0 Requires-Python >=3.7,<=3.11; 1.0.1 Requires-Python >=3.7,<=3.11; 1.0.2 Requires-Python >=3.7,<=3.11; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement torch==2.2.1+cu121 (from versions: 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1)
ERROR: No matching distribution found for torch==2.2.1+cu121
```

**Comment by osi1880vr** [comment]
The first error seems to be a connection issue during the download. The second thing I can not reproduce, I just did a clean clone and install and it just worked, thats the stupid developer telling "it working on my box" but also that stupid guy can not do anything else but try to understand the issue by trying to reproduce. Feel free to come to my discord and we try to figure it out. the whole process just worked. But I also had no issues downloading the large file from civit like you had.
